const ROADMAP = {
  title: "Python for Data Engineering",
  goal: "Transition into a Data Engineering role by 2027 (AWS/GCP, SEA or remote).",

  prerequisites: [
    {
      id: "prereq-git",
      text: "Comfortable with Git basics: clone, branch, commit, push, pull request",
      priority: "core",
    },
    {
      id: "prereq-sql",
      text: "Comfortable with basic SQL: SELECT, JOIN, GROUP BY, WHERE",
      priority: "core",
    },
  ],

  sqlHabit: {
    description:
      "15–20 min/day SQL practice (StrataScratch, DataLemur, or LeetCode SQL). Non-negotiable.",
    focus: [
      { weeks: "1–2", text: "Basic SELECT, JOIN types, GROUP BY, HAVING, aggregates" },
      { weeks: "3–4", text: "Window functions (ROW_NUMBER, RANK, LAG/LEAD), CTEs, subqueries" },
      { weeks: "5–6", text: "Query optimization, EXPLAIN plans, indexing basics" },
      { weeks: "7–8", text: "Mock interview SQL questions (timed, 20–30 min each)" },
    ],
    weeks: [1, 2, 3, 4, 5, 6, 7, 8],
  },

  components: [
    { id: "comp-w1-validators", week: 1, name: "validators.py (Pydantic)", reusedIn: "Capstone 1 Bronze ingestion" },
    { id: "comp-w1-fetcher", week: 1, name: "fetcher.py (HTTP client)", reusedIn: "Capstone 1 API extraction" },
    { id: "comp-w1-logger", week: 1, name: "logger.py", reusedIn: "Both capstones" },
    { id: "comp-w2-profiler", week: 2, name: "profiler.py (DQ report)", reusedIn: "Capstone 1 data quality" },
    { id: "comp-w3-loader", week: 3, name: "loader.py (SQLAlchemy)", reusedIn: "Both capstones Bronze load" },
    { id: "comp-w3-transformer", week: 3, name: "transformer.py", reusedIn: "Both capstones" },
    { id: "comp-w3-models", week: 3, name: "models/ (dimensional model sketch)", reusedIn: "Capstone 2 star schema" },
    { id: "comp-w4-dockerfile", week: 4, name: "Dockerfile + .env.example", reusedIn: "Both capstones Docker setup" },
    { id: "comp-w4-compose", week: 4, name: "docker-compose.yml", reusedIn: "Both capstones" },
    { id: "comp-w5-dag", week: 5, name: "dag_etl.py (Airflow DAG)", reusedIn: "Both capstones orchestration" },
    { id: "comp-w6-spark", week: 6, name: "spark_silver.py", reusedIn: "Capstone 2 Silver transform" },
    { id: "comp-w7-tests", week: 7, name: "tests/ + dbt/", reusedIn: "Both capstones production layer" },
    { id: "comp-w9-iac", week: 9, name: "terraform/ or IaC scripts (optional)", reusedIn: "Cloud deployment" },
  ],

  weeks: [
    {
      id: 1,
      title: "Python Core for Data Engineering",
      goal: "Validation, logging, HTTP, clean project structure.",
      days: [
        { day: 1, priority: "core", text: "Comprehensions, generators, decorators", doneDefault: true },
        { day: 2, priority: "core", text: "OOP for pipelines (classes, dataclasses)", doneDefault: true },
        { day: 3, priority: "core", text: "Error handling, logging, retry + exponential backoff", doneDefault: true },
        { day: 4, priority: "core", text: "Type hints + Pydantic v2 (validate API responses)", doneDefault: true },
        { day: 5, priority: "core", text: "File handling: CSV, JSON, JSONL" },
        { day: 6, priority: "core", text: "HTTP requests: pagination, error codes, rate limits, timeouts" },
        { day: 7, priority: "core", text: "Project structure, venv, .env + mini project finish" },
      ],
      miniProject: {
        name: "OpenAQ Air Fetcher",
        dod: [
          "Script runs end-to-end without crashing on bad data",
          "Pydantic rejects and logs at least one malformed record",
          "Output: air_quality.jsonl + air_quality.csv with 100+ records",
          "All secrets/config in .env (not hardcoded)",
          "README.md with setup instructions + example output",
        ],
        stretch: [
          "--city CLI arg (argparse)",
          "Summary log (X fetched, Y rejected, Z written)",
        ],
      },
      quiz: "Generators vs lists · decorator use cases · Pydantic field validation · logging levels · retry patterns · HTTP error handling.",
    },
    {
      id: 2,
      title: "Pandas & Polars",
      goal: "Modern data-manipulation stack (Pandas, Polars, DuckDB, Pandera).",
      days: [
        { day: 1, priority: "core", text: "Pandas core: groupby, merge, pivot" },
        { day: 2, priority: "core", text: "Pandas performance: chunked reads, dtypes, .pipe()" },
        { day: 3, priority: "exposure", text: "Polars fundamentals: LazyFrame, expressions, .collect()" },
        { day: 4, priority: "exposure", text: "Polars advanced: streaming, joins, aggregations" },
        { day: 5, priority: "exposure", text: "DuckDB: SQL on DataFrames/CSV/Parquet" },
        { day: 6, priority: "core", text: "Pandera validation + data profiling" },
        { day: 7, priority: "exposure", text: "Pandas vs Polars benchmark + mini project finish" },
      ],
      miniProject: {
        name: "Olist Data Profiler",
        dod: [
          "All 9 Olist CSVs profiled (null %, row counts, cardinality)",
          "HTML quality report generated + readable in browser",
          "Benchmark table: Pandas vs Polars for same operation",
          "3+ real DQ issues documented (column + description)",
        ],
        stretch: [
          "DuckDB profiling query + speed compare",
          "Pandera contract for olist_orders",
        ],
      },
      quiz: "LazyFrame eval · Pandera contracts · DuckDB use cases · memory optimization · merge join types.",
    },
    {
      id: 3,
      title: "ETL/ELT Scripting + Data Modeling + dbt Preview",
      goal: "Production-style ETL into PostgreSQL with idempotency + logging, grounded in dimensional design.",
      days: [
        { day: 1, priority: "core", text: "Extract patterns: API, CSV, DB reads" },
        { day: 2, priority: "core", text: "Transform: cleaning, type casting, dedup" },
        { day: 3, priority: "core", text: "Data modeling primer: star schema, fact vs. dimension, SCD Type 1/2 — sketch Olist star schema" },
        { day: 4, priority: "core", text: "SQLAlchemy Core (INSERT, UPSERT) + ORM essentials (lighter on ORM)" },
        { day: 5, priority: "exposure", text: "dlt fundamentals: pipeline, resource, destination" },
        { day: 6, priority: "core", text: "dbt preview: models/, sources.yml, ref(), first stg_ model" },
        { day: 7, priority: "core", text: "Idempotency + DQ checks + run logging + end-to-end + mini project finish" },
      ],
      miniProject: {
        name: "Bronze ETL Loader",
        dod: [
          "Runs twice: second run inserts 0 duplicates (verified in DB)",
          "1+ intentionally bad record caught, logged, skipped",
          "Bronze table in PostgreSQL with correct schema",
          "Run summary: Extracted: X | Rejected: Y | Loaded: Z",
          "Star schema sketch for Olist saved to /components/models/",
        ],
        stretch: [
          "--dry-run flag",
          "pipeline_runs audit table",
        ],
      },
      quiz: "UPSERT vs INSERT · idempotency · Core vs ORM · dlt resources · fact vs. dimension · SCD Type 1 vs 2 · quality check placement.",
    },
    {
      id: 4,
      title: "Cloud Storage & Docker",
      goal: "S3/MinIO archiving, incremental loads (watermark), Dockerize pipeline.",
      days: [
        { day: 1, priority: "exposure", text: "SQLAlchemy advanced: pooling, transactions, rollback" },
        { day: 2, priority: "core", text: "AWS S3 with boto3: upload, list, download" },
        { day: 3, priority: "exposure", text: "MinIO local setup (S3-compatible)" },
        { day: 4, priority: "core", text: "Incremental loads: watermark / MAX(updated_at)" },
        { day: 5, priority: "exposure", text: "CDC concepts + Debezium (conceptual)" },
        { day: 6, priority: "core", text: "Docker fundamentals: Dockerfile for Week 3 ETL" },
        { day: 7, priority: "core", text: "Docker Compose (PG + Python) + secrets + mini project finish" },
      ],
      miniProject: {
        name: "Dockerized Incremental Loader",
        dod: [
          "First run loads N; second run loads only new (delta verified)",
          "Raw JSON files appear in S3/MinIO after each run",
          "docker build + docker run complete without errors",
          "No hardcoded credentials (grep -r password . clean)",
        ],
        stretch: [
          "MinIO web UI check",
          "S3 key pattern raw/openaq/YYYY/MM/DD/run_{ts}.json",
        ],
      },
      quiz: "Watermark patterns · Docker layer caching · boto3 S3 ops · connection pooling · secrets mgmt.",
    },
    {
      id: 5,
      title: "Orchestration with Apache Airflow",
      goal: "Automated, scheduled, monitored pipelines (TaskFlow API).",
      days: [
        { day: 1, priority: "core", text: "Airflow setup (Docker Compose) + architecture" },
        { day: 2, priority: "core", text: "First DAG: Python tasks, schedule, manual trigger" },
        { day: 3, priority: "core", text: "TaskFlow API: rewrite Week 3 ETL" },
        { day: 4, priority: "core", text: "Connections, Variables, PostgresOperator" },
        { day: 5, priority: "exposure", text: "XComs, branching, conditional execution" },
        { day: 6, priority: "core", text: "Retries, SLAs, failure callbacks, monitoring" },
        { day: 7, priority: "exposure", text: "Data-aware scheduling (Datasets) + mini project finish" },
      ],
      miniProject: {
        name: "Scheduled OpenAQ Pipeline DAG",
        dod: [
          "DAG visible + triggerable in Airflow UI",
          "All 5 tasks succeed on manual trigger (graph view)",
          "Broken row-count check causes DAG failure (tested)",
          "DAG runs on schedule (catchup=False)",
        ],
        stretch: [
          "Slack/email failure notification",
          "SensorOperator waiting for S3 file",
        ],
      },
      quiz: "DAG scheduling · XCom limits · TaskFlow vs operators · backfill · connection types.",
    },
    {
      id: 6,
      title: "Big Data with PySpark",
      goal: "PySpark local mode, Silver transforms, Parquet output.",
      days: [
        { day: 1, priority: "core", text: "Spark architecture + PySpark local via Docker" },
        { day: 2, priority: "core", text: "DataFrame basics: read, select, filter, show" },
        { day: 3, priority: "core", text: "Transformations: withColumn, when, window functions" },
        { day: 4, priority: "core", text: "Aggregations, joins, null handling" },
        { day: 5, priority: "core", text: "Read PostgreSQL via JDBC + write Parquet" },
        { day: 6, priority: "exposure", text: "Partitioning, caching, broadcast joins" },
        { day: 7, priority: "exposure", text: "Delta Lake intro + mini project finish" },
      ],
      miniProject: {
        name: "Bronze to Silver Spark Transform",
        dod: [
          "PySpark job runs in Docker local mode without errors",
          "Parquet written with country=*/date=* partitions",
          "Row counts logged: Bronze in vs Silver out (+ rejection rate)",
          "Airflow DAG runs Spark job downstream of Bronze load",
        ],
        stretch: [
          "Delta Lake output",
          "Spark UI screenshot of job plan",
        ],
      },
      quiz: "Lazy eval · Parquet vs CSV · broadcast joins · Delta vs Parquet · JDBC performance.",
    },
    {
      id: 7,
      title: "Production-Grade Practices + dbt Deep Dive",
      goal: "Tests, dbt, CI/CD, observability — the production wrapper for both capstones.",
      days: [
        { day: 1, priority: "core", text: "pytest fundamentals: unit tests for transforms" },
        { day: 2, priority: "core", text: "Fixtures, parametrize, edge/bad-data tests" },
        { day: 3, priority: "exposure", text: "Integration tests against test DB + mocking API/S3" },
        { day: 4, priority: "core", text: "dbt deep dive I: staging models, ref()/source(), schema tests" },
        { day: 5, priority: "exposure", text: "dbt deep dive II: incremental models, macros/Jinja, dbt docs generate" },
        { day: 6, priority: "core", text: "Docker Compose full stack + GitHub Actions CI" },
        { day: 7, priority: "core", text: "Structured logging + observability + mini project finish" },
      ],
      miniProject: {
        name: "Production Hardening Sprint",
        dod: [
          "pytest passes with 80%+ coverage on transforms",
          "dbt run + dbt test pass with 0 failures",
          "docker compose up starts all services (Airflow, Postgres, MinIO)",
          "GitHub Actions CI badge green in README",
        ],
        stretch: [
          "dbt docs generate + lineage screenshot",
          "ruff lint as CI check",
        ],
      },
      quiz: "pytest fixtures vs parametrize · dbt ref() vs source() · incremental models · mocking · Compose deps · CI/CD stages.",
    },
    {
      id: 8,
      title: "Capstone Projects",
      goal: "Days 1–4 Capstone 1 · Days 5–7 Capstone 2 · prioritize Capstone 1.",
      days: [],
      capstones: [
        {
          id: "capstone1",
          name: "Capstone 1 — Olist E-Commerce Pipeline Modernization",
          priority: "core",
          items: [
            "GitHub repo: clean structure + .gitignore",
            "README: ASCII architecture diagram + one-command startup",
            "dbt docs generate screenshot (full lineage)",
            "1+ Power BI / SQL KPI screenshot",
            "dbt test exits 0 failures",
            "pytest CI badge green in README",
            "Airflow DAG screenshot (all tasks green)",
          ],
        },
        {
          id: "capstone2",
          name: "Capstone 2 — Adventure Works OLTP-to-OLAP Warehouse",
          priority: "exposure",
          items: [
            "GitHub repo: clean structure + .gitignore + README",
            "Star schema ERD in README (draw.io or ASCII)",
            "dbt docs generate screenshot (Gold lineage)",
            "Airflow DAG screenshot (all tasks green)",
            "Sample analytical SQL in README (top 10 products by revenue by region)",
            "pytest integration test passing in CI",
          ],
        },
      ],
      miniProject: null,
      quiz: null,
    },
    {
      id: 9,
      title: "Real Cloud Deployment Sprint",
      goal: "Move Capstone 1 onto real managed cloud infra (AWS or GCP). Core-level leverage for interviews.",
      days: [],
      cloudTracks: {
        aws: [
          "Day 1-2 — S3 (raw storage) + IAM roles/policies basics",
          "Day 3-4 — Redshift Serverless or RDS Postgres as warehouse",
          "Day 5 — Lambda or ECS Fargate + EventBridge schedule",
          "Day 6 — Wire Airflow (MWAA / EC2) or lightweight scheduler",
          "Day 7 — Cost check, teardown/cleanup script, screenshots for README",
        ],
        gcp: [
          "Day 1-2 — Cloud Storage (raw storage) + IAM basics",
          "Day 3-4 — BigQuery as warehouse",
          "Day 5 — Cloud Run or Cloud Functions + Cloud Scheduler",
          "Day 6 — Cloud Composer or lightweight scheduler",
          "Day 7 — Cost check, teardown/cleanup script, screenshots for README",
        ],
      },
      miniProject: {
        name: "Capstone 1, Live on Cloud",
        dod: [
          "Pipeline runs end-to-end on managed cloud services, not local Docker",
          "IAM roles scoped correctly (no * admin permissions used)",
          "Cost stays within free tier (verified in billing dashboard)",
          "Architecture diagram updated to show real cloud services",
          "Teardown script included (so you're not paying for idle resources)",
        ],
        stretch: [],
      },
      quiz: null,
    },
  ],
};
